// <auto-generated />
using System;
using Hospital.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hospital.DAL.Migrations
{
    [DbContext(typeof(HospitalContext))]
    [Migration("20230610121342_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hospital.DAL.Doctor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PerformanceRate")
                        .HasColumnType("int");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Specializatuon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7e614007-0646-47db-8294-256a136bb54f"),
                            Name = "Jessie",
                            PerformanceRate = 65,
                            Salary = 27064m,
                            Specializatuon = "Hematology"
                        },
                        new
                        {
                            Id = new Guid("66dd89dc-8c74-4f32-a498-683ae86fb9f2"),
                            Name = "Judy",
                            PerformanceRate = 32,
                            Salary = 18711m,
                            Specializatuon = "Neurology"
                        },
                        new
                        {
                            Id = new Guid("eb9ef91d-7500-401f-bfcf-4d3af0f9ec13"),
                            Name = "Naomi",
                            PerformanceRate = 27,
                            Salary = 32145m,
                            Specializatuon = "Pediatrics"
                        },
                        new
                        {
                            Id = new Guid("0ecfbf4a-43cb-43e3-bc1d-f65311329923"),
                            Name = "Joann",
                            PerformanceRate = 72,
                            Salary = 9232m,
                            Specializatuon = "Hematology"
                        },
                        new
                        {
                            Id = new Guid("b18ed37d-cd76-4b61-ba9d-4e44ae45b719"),
                            Name = "Judy",
                            PerformanceRate = 19,
                            Salary = 48498m,
                            Specializatuon = "Dermatology"
                        },
                        new
                        {
                            Id = new Guid("807c4fcd-4c2e-49af-85b1-d23b02fe0bb6"),
                            Name = "Alyssa",
                            PerformanceRate = 79,
                            Salary = 16586m,
                            Specializatuon = "Gastroenterology"
                        },
                        new
                        {
                            Id = new Guid("2925724d-fd2e-4358-bc5e-e4a2af0fcd57"),
                            Name = "Mable",
                            PerformanceRate = 5,
                            Salary = 33706m,
                            Specializatuon = "Infectious Disease"
                        },
                        new
                        {
                            Id = new Guid("ac8829b9-ecef-4b39-a8b4-be25c563c9ab"),
                            Name = "Paula",
                            PerformanceRate = 0,
                            Salary = 19094m,
                            Specializatuon = "Urology"
                        },
                        new
                        {
                            Id = new Guid("1eba0d36-22ba-4947-855d-f2d5f4bafa10"),
                            Name = "Rafael",
                            PerformanceRate = 97,
                            Salary = 12266m,
                            Specializatuon = "Pediatrics"
                        },
                        new
                        {
                            Id = new Guid("61547fa3-fdf4-46f4-be21-b02186b206e9"),
                            Name = "Sara",
                            PerformanceRate = 82,
                            Salary = 45041m,
                            Specializatuon = "Pediatrics"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
