// <auto-generated />
using System;
using Hospital.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hospital.DAL.Migrations
{
    [DbContext(typeof(HospitalContext))]
    partial class HospitalContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hospital.DAL.Doctor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PerformanceRate")
                        .HasColumnType("int");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Specializatuon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c74fab27-9d03-43d7-a99c-c5f25ba79987"),
                            Name = "Jessie",
                            PerformanceRate = 65,
                            Salary = 27064m,
                            Specializatuon = "Hematology"
                        },
                        new
                        {
                            Id = new Guid("6724a92b-ea27-40c1-adc3-d6667ea07ffc"),
                            Name = "Judy",
                            PerformanceRate = 32,
                            Salary = 18711m,
                            Specializatuon = "Neurology"
                        },
                        new
                        {
                            Id = new Guid("375447f8-f75b-4cd7-9129-b0a5d78332dc"),
                            Name = "Naomi",
                            PerformanceRate = 27,
                            Salary = 32145m,
                            Specializatuon = "Pediatrics"
                        },
                        new
                        {
                            Id = new Guid("c97a676a-e3ea-4c28-92a2-90f8d0dd521b"),
                            Name = "Joann",
                            PerformanceRate = 72,
                            Salary = 9232m,
                            Specializatuon = "Hematology"
                        },
                        new
                        {
                            Id = new Guid("9d3c4cbd-3248-47ca-8934-e4315c702e11"),
                            Name = "Judy",
                            PerformanceRate = 19,
                            Salary = 48498m,
                            Specializatuon = "Dermatology"
                        },
                        new
                        {
                            Id = new Guid("56f86e40-fcd8-4911-900c-7ae1255fc53a"),
                            Name = "Alyssa",
                            PerformanceRate = 79,
                            Salary = 16586m,
                            Specializatuon = "Gastroenterology"
                        },
                        new
                        {
                            Id = new Guid("f413b97d-1de4-4da9-8d2b-c93cea7b66f8"),
                            Name = "Mable",
                            PerformanceRate = 5,
                            Salary = 33706m,
                            Specializatuon = "Infectious Disease"
                        },
                        new
                        {
                            Id = new Guid("d474b19d-2da7-4249-a946-a4bd73eb1d8d"),
                            Name = "Paula",
                            PerformanceRate = 0,
                            Salary = 19094m,
                            Specializatuon = "Urology"
                        },
                        new
                        {
                            Id = new Guid("aa1e6135-fb7e-4649-9016-d8a8f96ce12c"),
                            Name = "Rafael",
                            PerformanceRate = 97,
                            Salary = 12266m,
                            Specializatuon = "Pediatrics"
                        },
                        new
                        {
                            Id = new Guid("0772f2d5-23ec-4540-a07f-4af793386b7d"),
                            Name = "Sara",
                            PerformanceRate = 82,
                            Salary = 45041m,
                            Specializatuon = "Pediatrics"
                        });
                });

            modelBuilder.Entity("Hospital.DAL.Issue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Issues");
                });

            modelBuilder.Entity("Hospital.DAL.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("IssuePatient", b =>
                {
                    b.Property<Guid>("IssuesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PatientsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IssuesId", "PatientsId");

                    b.HasIndex("PatientsId");

                    b.ToTable("IssuePatient");
                });

            modelBuilder.Entity("Hospital.DAL.Patient", b =>
                {
                    b.HasOne("Hospital.DAL.Doctor", "Doctor")
                        .WithMany("Patients")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("IssuePatient", b =>
                {
                    b.HasOne("Hospital.DAL.Issue", null)
                        .WithMany()
                        .HasForeignKey("IssuesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hospital.DAL.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hospital.DAL.Doctor", b =>
                {
                    b.Navigation("Patients");
                });
#pragma warning restore 612, 618
        }
    }
}
